-- AlterTable
ALTER TABLE "Character"
ADD COLUMN "hunger" INTEGER NOT NULL DEFAULT 80,
ADD COLUMN "thirst" INTEGER NOT NULL DEFAULT 80,
ADD COLUMN "sleep" INTEGER NOT NULL DEFAULT 80,
ADD COLUMN "energy" INTEGER NOT NULL DEFAULT 80,
ADD COLUMN "routineUpdatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "lastWorkAt" TIMESTAMP(3),
ADD COLUMN "workStreak" INTEGER NOT NULL DEFAULT 0;
